# Generated by Django 2.1 on 2019-04-30 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='write',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
